### ISSUE TITLE
'VideoSet' object has no attribute 'sample_width'

### ISSUE THREAD

**Issue by jjtail** [tridivb/slowfast_feature_extractor#5]
Hi,  I have some problems when I follow the steps
Traceback (most recent call last):
  File "run_net.py", line 131, in <module>
    main()
  File "run_net.py", line 127, in main
    test(cfg=cfg)
  File "/home/dutir/zengjingjie/slowfast_feature_extractor/test_net.py", line 169, in test
    cfg, path_to_vid, vid_id, read_vid_file=cfg.DATA.READ_VID_FILE
  File "/home/dutir/zengjingjie/slowfast_feature_extractor/datasets/videoset.py", line 52, in __init__
    self.frames = self._get_frames()
  File "/home/dutir/zengjingjie/slowfast_feature_extractor/datasets/videoset.py", line 90, in _get_frames
    (self.sample_width, self.sample_height),
AttributeError: 'VideoSet' object has no attribute 'sample_width'

**Comment by tridivb** [comment]
Hi, 

Thanks for using the framework. Could you please follow the Issue Template and provide some more information on how to reproduce the issue and your system configuration?

**Comment by tridivb** [comment]
Backtracking from your error, it seems the sample_width and sample_height are probably not asiggned any values properly. These need to be set using the sample_size parameter in the config file. 

If you are using a different config file from the one provided, don't forget to include the ones mentioned in the Readme. Some of the parameters have been added while building the framework, so they won't exist in the default ones provided by the main PySlowFast framework.

**Comment by jjtail** [comment]
> Backtracking from your error, it seems the sample_width and sample_height are probably not asiggned any values properly. These need to be set using the sample_size parameter in the config file.
> 
> If you are using a different config file from the one provided, don't forget to include the ones mentioned in the Readme. Some of the parameters have been added while building the framework, so they won't exist in the default ones provided by the main PySlowFast framework.

Thank for your reply,

I first noticed that it was a problem with the torch version. When I upgraded the torch to 1.3, the same problem still occurred. This is my config, please check it out.
TRAIN:
  ENABLE: False
  DATASET: videoset
  CHECKPOINT_FILE_PATH: "/home/zhangshuchen/slowfast_feature_extractor/checkpoints/SLOWFAST_8x8_R50.pkl"
  CHECKPOINT_TYPE: caffe2
DATA:
  PATH_TO_DATA_DIR: "/home/zhangshuchen/slowfast_feature_extractor/asda"
  PATH_PREFIX: "/home/zhangshuchen/slowfast_feature_extractor/asda"
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  IN_FPS: 15
  OUT_FPS: 15
  READ_VID_FILE: True
  VID_FILE_EXT: ".mp4"
  IMG_FILE_EXT: ""
  IMG_FILE_FORMAT: ""
  SAMPLE_SIZE: [256,256]
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 7
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
  MOMENTUM: 0.1
  WEIGHT_DECAY: 0.0
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 37
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 400
  ARCH: slowfast
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: videoset
  BATCH_SIZE: 3
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: "/home/zhangshuchen/slowfast_feature_extractor/out"

**Comment by tridivb** [comment]
As long as you installed all the pre-requisties for PyTorch, PySlowFast and this framework, it should not be an issue. Besides that, this looks strange. The values are the same the ones provided in my config file. The only difference I see is no indentations. But am not sure if your config file itself is like that or the github comment section messed up what you copied. Could you attach the config file here?

**Comment by jjtail** [comment]
> As long as you installed all the pre-requisties for PyTorch, PySlowFast and this framework, it should not be an issue. Besides that, this looks strange. The values are the same the ones provided in my config file. The only difference I see no indentations for each section. eg. The Data section should be like this,
> 
> ```
> DATA:
>   PATH_TO_DATA_DIR: "/media/data/tridiv/epic_kitchens/EPIC_KITCHENS_2018"
>   PATH_PREFIX: "frames_rgb_flow/rgb"
>   NUM_FRAMES: 32
>   SAMPLING_RATE: 2
>   TRAIN_JITTER_SCALES: [256, 320]
>   TRAIN_CROP_SIZE: 224
>   TEST_CROP_SIZE: 256
>   INPUT_CHANNEL_NUM: [3, 3]
>   IN_FPS: 60
>   OUT_FPS: 30
>   READ_VID_FILE: False
>   VID_FILE_EXT: ".MP4"
>   IMG_FILE_EXT: ".jpg"
>   IMG_FILE_FORMAT: "frame_{:010d}.jpg"
>   SAMPLE_SIZE: [256, 256]
> ```
> 
> But am not sure if your config file itself is like that or the github comment section messed up what you copied. Could you attach the config file here?

Alright. 
When I put the 52 lines of code in your datasets/videoset.py behind the lines 54-61, everything will run. 
thank you

**Comment by tridivb** [comment]
Welcome. 

Do you mean moving the following section before the class definition?

```
        if isinstance(cfg.DATA.SAMPLE_SIZE, list):
            self.sample_width, self.sample_height = cfg.DATA.SAMPLE_SIZE
        elif isinstance(cfg.DATA.SAMPLE_SIZE, int):
            self.sample_width = self.sample_height = cfg.DATA.SAMPLE_SIZE
        else:
            raise Exception(
                "Error: Frame sampling size type must be a list [Height, Width] or int"
            )
```

Yes that should work. But that does not make it clear why it did not work in the first place. It should have. The only thing I can think of right now is that the the config file is not set properly or there is some problem while reading it. 

Am glad that you were able to figure it out and so am closing the issue.

**Comment by jjtail** [comment]
Hello, I still put my config below, I am slightly modified according to the style you gave. Only modified my file directory. 
Thanks again for your answer, your open source project is very helpful to me.

```
> TRAIN:
>   ENABLE: False
>   DATASET: videoset
>   CHECKPOINT_FILE_PATH: "/home/zhangshuchen/slowfast_feature_extractor/checkpoints/SLOWFAST_8x8_R50.pkl"
>   CHECKPOINT_TYPE: caffe2
> DATA:
>   PATH_TO_DATA_DIR: "/home/zhangshuchen/slowfast_feature_extractor/asda"
>   PATH_PREFIX: ""
>   NUM_FRAMES: 32
>   SAMPLING_RATE: 2
>   TRAIN_JITTER_SCALES: [256, 256]
>   TRAIN_CROP_SIZE: 256
>   TEST_CROP_SIZE: 256
>   INPUT_CHANNEL_NUM: [3, 3]
>   IN_FPS: 30
>   OUT_FPS: 30
>   READ_VID_FILE: True
>   VID_FILE_EXT: ".mp4"
>   IMG_FILE_EXT: ""
>   IMG_FILE_FORMAT: ""
>   SAMPLE_SIZE: [256,256]
> SLOWFAST:
>   ALPHA: 4
>   BETA_INV: 8
>   FUSION_CONV_CHANNEL_RATIO: 2
>   FUSION_KERNEL_SZ: 7
> RESNET:
>   ZERO_INIT_FINAL_BN: True
>   WIDTH_PER_GROUP: 64
>   NUM_GROUPS: 1
>   DEPTH: 50
>   TRANS_FUNC: bottleneck_transform
>   STRIDE_1X1: False
>   NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
> NONLOCAL:
>   LOCATION: [[[], []], [[], []], [[], []], [[], []]]
>   GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
>   INSTANTIATION: dot_product
> BN:
>   USE_PRECISE_STATS: True
>   NUM_BATCHES_PRECISE: 200
>   MOMENTUM: 0.1
>   WEIGHT_DECAY: 0.0
> SOLVER:
>   BASE_LR: 0.1
>   LR_POLICY: cosine
>   MAX_EPOCH: 196
>   MOMENTUM: 0.9
>   WEIGHT_DECAY: 1e-4
>   WARMUP_EPOCHS: 37
>   WARMUP_START_LR: 0.001
>   OPTIMIZING_METHOD: sgd
> MODEL:
>   NUM_CLASSES: 400
>   ARCH: slowfast
>   LOSS_FUNC: cross_entropy
>   DROPOUT_RATE: 0.5
> TEST:
>   ENABLE: True
>   DATASET: videoset
>   BATCH_SIZE: 1
> DATA_LOADER:
>   NUM_WORKERS: 8
>   PIN_MEMORY: True
> NUM_GPUS: 1
> NUM_SHARDS: 1
> RNG_SEED: 0
> OUTPUT_DIR: "/home/zhangshuchen/slowfast_feature_extractor/out"
```

**Comment by tridivb** [comment]
You are welcome. I hope everything worked out in the end.
